# Generated by Django 4.2 on 2023-04-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
            options={"db_table": "Category", "managed": True,},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=45)),
                ("desc", models.TextField()),
                ("created_by", models.CharField(max_length=30, null=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="home.category",
                    ),
                ),
            ],
            options={"db_table": "Article", "managed": True,},
        ),
    ]
